# Database Properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5757/
    username: postgres
    password: postgres

telegram.bot.token:

auth.encoder:
  password: 57
  iterations: 20