# Database Properties
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

telegram.bot.token: ${TOKEN}

auth.encoder:
  password: ${PASSWORD}
  iterations: ${ITERATIONS}